name = "AbstractExample"
uuid = "eab7a7e1-81d0-4782-81dc-04bd24a17522"
authors = ["Eric Berquist <eric.berquist@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
