# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider "virtualbox" do |provider|
        provider.cpus = 1
        provider.memory = 1024
    end
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "vagrant.yml"
    end
end
